config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'podcasts#index'
  resources :podcasts, only: [:index, :new, :create, :show, :edit, :update, :delete]
  resources :genres, only: :index
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :podcasts, only: [:index, :create, :show]
      resources :reviews, only: :create
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  has_many :reviews

  validates :name, presence: true
  validates :publisher, presence: true
  validates :description, presence: true
  validates :link, :format => URI::regexp(%w(http https))
  validates :image, :format => URI::regexp(%w(http https))
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :podcast
  belongs_to :user

  validates :rating, presence: true, inclusion: { in: 1..5 }
  validates :body, presence: true, length: { maximum: 2000, minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :profile_photo, ProfilePhotoUploader

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/podcasts_controller.rb
class Api::V1::PodcastsController < ApplicationController
  serialization_scope :current_user
  protect_from_forgery unless: -> { request.format.json? }

  def index
    render json: Podcast.all
  end

  def show
    render json: Podcast.find(params[:id])
  end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  def create
    review = Review.new(review_params)
    review.user = current_user
    if review.save
      render json: review
    else
      render json: { error: review.errors.full_messages }
    end
  end

  private
  def review_params
    params.require(:review).permit(:rating, :body, :podcast_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:profile_photo])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :authorize_user, except: [:index, :show, :new, :create]
  before_action :authorize_admin, only: [:edit]

  def index
    @podcasts = Podcast.all
  end

  def show
    @podcast = Podcast.find(params[:id])
  end

  def new
    @podcast = Podcast.new
  end

  def create
    @podcast = Podcast.new(podcast_params)

    if @podcast.save
      redirect_to @podcast
      flash[:notice] = "Podcast added successfully"
    else
      render :'new'
    end
  end

  def edit
    @podcast = Podcast.find(params[:id])
  end

  def update
    @podcast = Podcast.find(params[:id])
    if @podcast.update(podcast_params)
      redirect_to @podcast, notice: "Podcast was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @podcast = Podcast.find(params[:id])
    @podcast.destroy
    redirect_to podcasts_path, notice:  "Podcast was successfully deleted."
  end

  private
  def podcast_params
    params.require(:podcast).permit(:name, :description, :publisher, :link, :image)
  end

  def authorize_user
    if current_user == nil
      flash[:notice] = "You do not have access to this page."
      redirect_to root_path
    end
  end

  def authorize_admin
    if !current_user.admin?
      flash[:notice] = "You do not have access to this page."
      redirect_to root_path
    end
  end
end

app/views/genres/index.html.erb
<h1>All Genres</h1>

<ul>
  <% @genres.each do |genre| %>
    <li>
      <%= link_to genre.name %>
    </li>
  <% end %>
</ul>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PodcastR</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Nunito:600" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/"><i class="fas fa-headphones"></i> PodcastR</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">

        <%- if current_user -%>
          <li class="devise-nav-bar"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li class="devise-nav-bar"><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li class="devise-nav-bar"><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <div>
    <% if current_user && current_user.profile_photo.url%>
      <img class="prof-pic" src="<%=current_user.profile_photo.url%>">
    <% end %>
  </div>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <div id="main-yield-box">
    <%= yield %>
  </div>


  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>

app/views/podcasts/edit.html.erb
<div class="podcast-new-form-container">
  <h2 class="new-podcast-form-title">Edit Podcast</h2>

  <ul>
    <%@podcast.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    </ul>
  <%end%>

  <%= form_for(@podcast) do |f|%>

  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :publisher %><br />
    <%= f.text_field :publisher %>
  </div>

  <div>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>

  <div>
    <%= f.label :image, "Image URL" %><br />
    <%= f.text_field :image %>
  </div>

  <div>
    <%= f.submit "Update Podcast" %>
  </div>
  <%end%>
</div>

app/views/podcasts/index.html.erb
<div id="app">
</div>

<div class="small-12 columns">
  <div id="submit-podcast-button" class="small-6 small-centered columns">
    <%= link_to "Submit New Podcast", new_podcast_path %>
  </div>
</div>

app/views/podcasts/new.html.erb
<div class="podcast-new-form-container">
  <h2 class="new-podcast-form-title">New Podcast Form</h2>

  <ul>
    <%@podcast.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    </ul>
  <%end%>

  <%= form_for(@podcast) do |f|%>

  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :publisher %><br />
    <%= f.text_field :publisher %>
  </div>

  <div>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>

  <div>
    <%= f.label :image, "Image URL" %><br />
    <%= f.text_field :image %>
  </div>

  <div>
    <%= f.submit "Add Podcast" %>
  </div>
  <%end%>
</div>

app/views/podcasts/show.html.erb
<div id="app">
</div>